[package]
name = "cryptenv"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
keyring = { version = "3.2.1", features = ["apple-native"] }
serde = { version = "1.0.209", features = ["derive"] }
shellexpand = "3.1.0"
toml = "0.8.19"
